name: presentation
description: presentation layer
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  app_resources:
    path: ../app_resources
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^8.0.2
  auto_route: ^9.2.2
  injectable: ^2.5.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator:
  injectable_generator:   


